CREATE DATABASE DIU;

USE DIU;

CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CGPA FLOAT,
    CITY VARCHAR(50)
);

CREATE TABLE FAKIBUZ_STUDENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CGPA FLOAT,
    CITY VARCHAR(50)
);

DROP TABLE FAKIBUZ_STUDENT;

INSERT INTO STUDENT(ID, NAME, CGPA, CITY)VALUES
(1,'Hridoy Hasan', 3.50, 'Dhaka'),
(2,'Ronaldo', 3.91, 'Al-Nassr FC'),
(3,'Tom', 3.50, 'Dhaka'),
(4,'Messi', 3.91, 'Inter Miami');

SELECT * FROM student;

SELECT ID, CITY FROM STUDENT;
SELECT ID, CITY FROM STUDENT WHERE ID = 2;
SELECT NAME FROM STUDENT WHERE CITY = 'DHAKA';

-- Update data from table

UPDATE STUDENT
SET CGPA = 3.78 WHERE ID = 1;

DELETE FROM STUDENT WHERE ID = 3;

# DROP, DELETE, TRUNCATE
# DROP (Delete the database or Delete the table)
# DELETE it used for deleting a row, column or elements of row column
# TRUNCATE (Cleaning the table) Table thakbe but data will be removed

# ALTER TABLE STUDENT
-- ADD COLUMN SECTION VARCHAR(1) DEFAULT 'A';

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD COLUMN SECTION VARCHAR(1) DEFAULT 'A';

SELECT * FROM STUDENT WHERE NAME = 'Hridoy' OR CITY = 'Dhaka';

SELECT * FROM STUDENT WHERE NOT CITY = 'Dhaka';
# SELECT * FROM STUDENT WHERE CITY != 'Dhaka';

SELECT * FROM STUDENT WHERE CGPA > 3.20 AND CGPA < 3.80;
# SELECT * FROM STUDENT WHERE CGPA  3.20 AND 3.80;

SELECT * FROM STUDENT WHERE CITY IN ('Dhaka', 'Al-Nassr FC');

SELECT DISTINCT(CITY) FROM STUDENT;

# LIKE _ %
SELECT * FROM STUDENT WHERE NAME LIKE 'H%';
SELECT * FROM STUDENT WHERE NAME LIKE 'I%';