-- Active: 1738684170210@@127.0.0.1@3306@college
-- Creating Database
CREATE DATABASE COLLEGE;

-- Select Database (You can have multiple db, so you have to select your specific DB)
USE COLLEGE;

-- Creating Table
CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SECTION VARCHAR(1),
    AGE INT CHECK (AGE > 18),
    CITY VARCHAR(50) DEFAULT 'DHAKA'
);

INSERT INTO STUDENT(ID, NAME, SECTION, AGE, CITY)VALUES
(1826, "Hridoy Hasan", 'A', 22, 'Dhaka')

SELECT * FROM STUDENT; -- * MEANS ALL 

SELECT ID, NAME, AGE FROM STUDENT;

INSERT INTO STUDENT(ID, NAME, SECTION, AGE, CITY)VALUES
(1827, "John Doe", 'A', 22, 'Dhaka'),
(1828, "Jean Doe", 'A', 22, 'Dhaka')

SELECT * FROM STUDENT;

SELECT * FROM STUDENT WHERE ID = 1826;

SELECT NAME  FROM STUDENT WHERE SECTION='A';

ALTER TABLE STUDENT ADD COLUMN CGPA FLOAT;