CREATE DATABASE IF NOT EXISTS FOOTBALL_ASSOCIATION;
SHOW DATABASES;

USE FOOTBALL_ASSOCIATION;

CREATE TABLE IF NOT EXISTS PLAYERS(
    PLAYER_NUMBER INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CLUB VARCHAR(50),
    SALARY INT DEFAULT 0
);

SELECT * FROM PLAYERS;

INSERT INTO PLAYERS(PLAYER_NUMBER, NAME, CLUB, SALARY) VALUES
(7, 'Ronaldo', 'Al-Nassr FC', 1700000),
(10, 'Messi', 'Paris Saint-Germain', 4100000),
(9, 'Lewandowski', 'Barcelona', 2000000),
(11, 'Neymar', 'Paris Saint-Germain', 3600000),
(1, 'Neuer', 'Bayern Munich', 1500000);


# SEE SPECIFIC COLUMN

SELECT NAME, CLUB FROM PLAYERS;
SELECT NAME FROM PLAYERS WHERE SALARY > 1700000 AND SALARY < 4100000;
UPDATE PLAYERS
SET SALARY = 2700000 WHERE PLAYER_NUMBER = 7;

DELETE FROM PLAYERS WHERE NAME = 'Neuer';
UPDATE PLAYERS
SET CLUB = 'Barcelona' WHERE PLAYER_NUMBER = 9;

ALTER TABLE PLAYERS ADD COLUMN CITY VARCHAR(50) DEFAULT 'Dhaka';

SELECT * FROM PLAYERS WHERE `PLAYER_NUMBER` > 7 AND `PLAYER_NUMBER` < 11;

ALTER TABLE PLAYERS ADD COLUMN PLAYER_COUNTRY VARCHAR(50) DEFAULT 'Bangladesh';
ALTER TABLE PLAYERS ADD COLUMN SIGNING_DATE DATE DEFAULT '2024-05-23';
SELECT * FROM PLAYERS;