CREATE DATABASE TECH_SHOP;
USE TECH_SHOP;

CREATE TABLE SALES(
    ID INT PRIMARY KEY,
    CATEGORY VARCHAR(50) NOT NULL,
    AMOUNT INT
);

INSERT INTO SALES(ID, CATEGORY, AMOUNT) VALUES
(1, 'Laptop', 500),
(2, 'Mobile', 200),
(3, 'Laptop', 700),
(4, 'Mobile', 300),
(5, 'Tablet', 400);

SELECT * FROM SALES;
SELECT SUM(AMOUNT), CATEGORY FROM SALES GROUP BY CATEGORY;
SELECT MAX(AMOUNT), CATEGORY FROM SALES GROUP BY CATEGORY;
SELECT MIN(AMOUNT), CATEGORY FROM SALES GROUP BY CATEGORY;
SELECT COUNT(AMOUNT), CATEGORY FROM SALES GROUP BY CATEGORY;
SELECT COUNT(AMOUNT), CATEGORY FROM SALES GROUP BY CATEGORY HAVING CATEGORY = 'Laptop';