CREATE DATABASE UnivarsityDB;
USE UnivarsityDB;
CREATE TABLE Students(
  StudentID INT PRIMARY KEY,
    Name VARCHAR(50),
    Age INT CHECK(Age > 0),
    Department VARCHAR(30),
    CGPA DECIMAL(3,2)
);

SELECT * FROM Students;

INSERT INTO Students(StudentID, Name, Age, Department, CGPA)
VALUE
(1001,'Ali', 50, 'CSE', 3.669 );

INSERT INTO Students(StudentID, Name, Age, Department, CGPA)
VALUES
(1002, 'Asif', 19, 'Phycology', 3.80),
(1554, 'Nawshin Zaman', 22, 'CSE', 3.93),
(1003, 'Alice', 24, 'SWE', 3.10);

SELECT * FROM Students;

INSERT INTO Students(StudentID, Name, Age, Department, CGPA)
VALUES
(1004,'ALI KHAN', 22, 'COMPUTER SCIENCE',3.80),
(1005,'SARAH AHMED', 21, 'MATHEMATICS',3.65),
(1006, 'JOHN DOE', 23, 'PHYSICS', 3.45);

SELECT * FROM Students WHERE Age <= 22;
SELECT * FROM Students WHERE DepArtment = 'CSE' OR Department = 'Computer Science';
SELECT * FROM Students WHERE CGPA BETWEEN 3.5 AND 4.0 AND DEPARTMENT ='CSE' AND AGE <= 25;
SELECT * FROM Students;
DELETE FROM Students  WHERE StudentID = 1004;


-- REMOVE ALL VALUE FROM TABLE BUT KEEPING THE STRUCT
TRUNCATE TABLE STUDENTS;

-- DELETE THE WHOLE TABLE WITH  STRUCT
DROP TABLE STUDENTS;

ALTER TABLE STUDENTS ADD Email VARCHAR(50);

ALTER TABLE STUDENTS MODIFY AGE SMALLINT;
ALTER TABLE STUDENTS MODIFY AGE INT;
ALTER TABLE STUDENTS RENAME UnivarsityStudents;
ALTER TABLE uNIVARSITYSTUDENTS RENAME STUDENTS;
ALTER TABLE STUDENTS DROP Email;

SELECT * FROM STUDENTS;

ALTER TABLE STUDENTS ADD COLUMN RMAIL VARCHAR(50);

SELECT * FROM STUDENTS WHERE DEPARTMENT = 'CSE' OR DEPARTMENT = 'MATHEMATICS' AND CGPA > 3.5;

-- find students whos names start with A
SELECT * FROM  STUDENTS WHERE NAME LIKE 'A%' OR NAME LIKE 'N%';

-- Find the names ends with n
SELECT * FROM STUDENTS WHERE NAME LIKE '%N' OR NAME LIKE '%F';

-- Find studens whose name has nz anywhere
SELECT * FROM STUDENTS WHERE NAME LIKE '%A%';

-- Find studnet whose name has exactly 4 char
SELECT * FROM STUDENTS WHERE NAME LIKE '____'; -- HERE WE HAVE USED 4 _  

-- Find all students whose second letter is a
SELECT * FROM STUDENTS WHERE NAME LIKE '_A%';  

SELECT * FROM STUDENTS;

ALTER TABLE STUDENTS CHANGE RMAIL EMAIL VARCHAR(50);

INSERT INTO STUDENTS(STUDENTID, NAME, AGE, DEPARTMENT, CGPA)
VALUE
(1004, 'OMRITO', 24, 'COMPUTER SCIENCE', 3.89);

UPDATE STUDENTS SET EMAIL = 'zaman2305101554@diu.edu.bd' WHERE STUDENTID = '1554';

set sql_safe_updates = 0;
UPDATE STUDENTS SET DEPARTMENT = 'CSE' WHERE DEPARTMENT = 'COMPUTER SCIENCE';
set sql_safe_updates = 1;

UPDATE STUDENTS SET DEPARTMENT = 'COMPUTER SCIENCE' WHERE STUDENTID = 1554;
SET SQL_SAFE_UPDATES = 0;
UPDATE STUDENTS SET DEPARTMENT = 'COMPUTER SCIENCE' WHERE DEPARTMENT ='CSE';
SET SQL_SAFE_UPDATES = 1; 