CREATE DATABASE UniDB;
USE UniDB;
CREATE TABLE STUDENTS(
    STUDENTID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT CHECK(AGE >= 18),
    CGPA DECIMAL(3,2)
);

ALTER TABLE STUDENTS ADD COLUMN DEPARTMENT VARCHAR(50);
SELECT * FROM STUDENTS;

# Insert a single row
INSERT INTO STUDENT(STUDENTID, NAME, AGE, CGPA, DEPARTMENT)VALUE
(1, 'John Doe', 20, 3.5, 'Computer Science');
