CREATE DATABASE SSNIC_DB;
USE SSNIC_DB;

CREATE TABLE STUDENT(
    S_ID INT PRIMARY KEY,
    S_NAME VARCHAR(50) NOT NULL,
    S_DOB DATE,
    CGPA DECIMAL(3,2)
);

RENAME TABLE STUDENT TO STUDENT_INFO;

SELECT * FROM STUDENT_INFO;

ALTER TABLE STUDENT_INFO ADD COLUMN PHONE_NUMBER INT;

ALTER TABLE STUDENT_INFO RENAME COLUMN PHONE_NUMBER TO EMAIL;

ALTER TABLE STUDENT_INFO MODIFY COLUMN EMAIL VARCHAR(50);

ALTER TABLE STUDENT_INFO MODIFY COLUMN EMAIL VARCHAR(50) AFTER S_NAME;

ALTER TABLE STUDENT_INFO DROP COLUMN S_DOB;