# CREATE DATABASE, USE DATABSE, CREATE TABLE, INSERT INTO
# UPDATE TABLE, ALTER TABLE, DELETE FROM, TRUNCATE TABLE
# DROP TABLE

CREATE DATABASE bd_db;
USE bd_db;

CREATE TABLE Customer(
    CID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50),
    Age INT
);

CREATE TABLE Product(
    PID INT PRIMARY KEY AUTO_INCREMENT,
    P_Name VARCHAR(50),
    CID INT,
    FOREIGN KEY (CID) REFERENCES Customer(CID)
);

SELECT * FROM Product;
