USE example_db;

SELECT * FROM CUSTOMERS 
ORDER BY NAME;

SELECT * FROM CUSTOMERS 
ORDER BY NAME DESC;

SELECT * FROM CUSTOMERS
ORDER BY ADDRESS, NAME;

SELECT * FROM CUSTOMERS 
ORDER BY AGE ASC, SALARY DESC;

SELECT * FROM CUSTOMERS 
ORDER BY LENGTH(ADDRESS) ASC;
