CREATE DATABASE SSNIC;
USE SSNIC;

CREATE TABLE STUDENTS_INFO(
    S_ID INT PRIMARY KEY,
    S_NAME VARCHAR(50),
    S_CGPA DECIMAL(3,2),
    SECTION VARCHAR(1)
);

SELECT * FROM STUDENTS_INFO;

RENAME TABLE STUDENTS_INFO TO STUDENTS;

SELECT * FROM STUDENTS;

ALTER TABLE STUDENTS ADD COLUMN PHONE_NUMBER VARCHAR(50);

-- RENAME WITH VARIABLE DOES NOT SUPPORT 

-- ALTER TABLE STUDENTS RENAME COLUMN PHONE_NUMBER TO EMAIL VARHCAR(100); -- THIS WILL NOT SUPPORT

-- RENAME WITHOUT VARIABLE SUPPORTS 
ALTER TABLE STUDENTS RENAME COLUMN PHONE_NUMBER TO EMAIL;

ALTER TABLE STUDENTS MODIFY COLUMN EMAIL VARCHAR(100);

ALTER TABLE STUDENTS MODIFY COLUMN EMAIL VARCHAR(100) AFTER S_ID;

ALTER TABLE STUDENTS ADD COLUMN PHONE_NUMBER INT;

ALTER TABLE STUDENTS DROP COLUMN S_ID;