SHOW DATABASES;
CREATE DATABASE SCHOOL_DB;

DROP DATABASE myDB; -- myDB IS IN READ ONLY MODE.

-- MAKE DATABSE READ ONLY MODE.

-- ALTER DATABASE SCHOOL_DB READ ONLY = 1;

-- MAKE DATABSE EDIT MODE.
-- ALTER DATABASE SCHOOL_DB READ ONLY = 0;