CREATE DATABASE COMP_DB;

USE COMP_DB;

-- CREATE TABLE IN THE DB
CREATE TABLE EMPLOYEES(
    EMP_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    second_NAME VARCHAR(50),
    HOURLY_PAY DECIMAL(5,2),
    HIRE_DATE DATE
);

SELECT * FROM employees;

-- RENAME TABLE 
RENAME TABLE EMPLOYEES TO COM_EMPLOYEES;
SELECT * FROM COM_EMPLOYEES;

-- ADD A NEW COLUMN
ALTER TABLE COM_EMPLOYEES ADD PHONE_NUMBER VARCHAR(50);

-- RENAME A COLUMN
ALTER TABLE COM_EMPLOYEES RENAME COLUMN PHONE_NUMBER TO EMAIL;

ALTER TABLE COM_EMPLOYEES MODIFY COLUMN EMAIL VARCHAR(50);

ALTER TABLE COM_EMPLOYEES CHANGE COLUMN EMAIL EMAIL VARCHAR(50) AFTER EMP_ID;

ALTER TABLE COM_EMPLOYEES MODIFY COLUMN EMAIL VARCHAR(50) FIRST;

ALTER TABLE com_employees DROP COLUMN EMAIL;